"""empty message

Revision ID: 8ea701180c66
Revises: 3b327cf85c18
Create Date: 2017-09-20 18:19:51.308185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea701180c66'
down_revision = '3b327cf85c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppinglists', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('shoppinglists', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoppinglists', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('shoppinglists', 'title')
    # ### end Alembic commands ###
